name: Integração contínua

on: [pull_request]

jobs:
  e2e-tests:
    name: Rodar testes E2E
    runs-on: ubuntu-18.04

    steps:
      - name: Puxar o código do commit
        uses: actions/checkout@v2

      - name: Instalar o Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Instalar as dependências do npm
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: reports/coverage/lcov.info

  commit-lint:
    name: Executar lint das mensagens de commit
    runs-on: ubuntu-18.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v2.1.6
      with:
        helpURL: https://github.com/BrasilAPI/BrasilAPI/blob/master/CONTRIBUTING.md
